// Package aipatterns: entropy-based secret detection.
//
// The regex rules in rules.go catch secrets with a known shape (AWS keys,
// private key headers, "token=..." literals). Real secrets generated by a
// service (API keys, session tokens, base64-encoded credentials) often have
// no recognizable prefix at all — the only signal left is that they look
// random. Shannon entropy over the candidate token's characters approximates
// "looks random": natural-language prose, code identifiers, and short hex/
// URL fragments all sit well under the threshold used here, while
// high-entropy alnum/base64-shaped runs sit above it.
package aipatterns

import (
	"fmt"
	"math"
	"regexp"

	"github.com/YellowFoxH4XOR/dwarpal/internal/finding"
	"github.com/YellowFoxH4XOR/dwarpal/internal/gitio"
)

// entropyMinLen is the shortest token this rule considers. Below this,
// hex color codes, short base64-looking strings, and other everyday
// short tokens would generate noise; the PRD-cited real secrets are all
// longer than this.
const entropyMinLen = 20

// entropyThreshold is the minimum Shannon entropy (bits/char) a token must
// have, on top of meeting entropyMinLen, to be flagged. Natural-language
// prose and typical camelCase/snake_case identifiers land below ~4.0
// bits/char; base64 and random alnum secrets land above it.
const entropyThreshold = 4.0

// candidateTokenPattern finds maximal runs of the secret-shaped charset:
// letters, digits, and the symbols base64/URL-safe-base64 and common
// token encodings use. Quotes, spaces, and punctuation outside this set
// naturally terminate a run, so this one pattern covers both quoted
// string literals and bare tokens without needing separate handling.
var candidateTokenPattern = regexp.MustCompile(`[A-Za-z0-9+/=_-]{20,}`)

// urlPattern strips URLs before token scanning: mixed-case path segments
// (github.com/SomeOrg/repo) legitimately score above the entropy threshold
// but are addresses, not credentials. Any secret embedded in a URL would be
// caught by the assigned-literal shape rule instead.
var urlPattern = regexp.MustCompile(`\bhttps?://\S+|\bwww\.\S+`)

// hasDigit gates the entropy rule: machine-generated secrets essentially
// always mix digits into the token, while long human identifiers
// (TestCache_WarmRebuildPreservesShingles scored 4.2 bits/char and blocked a
// real commit) usually don't. Requiring a digit removes the identifier
// false-positive class at negligible recall cost.
func hasDigit(tok string) bool {
	for _, c := range tok {
		if c >= '0' && c <= '9' {
			return true
		}
	}
	return false
}

// pathLike reports whether a token reads as a filesystem/URL path rather
// than an encoded credential: multiple '/' separators with no other base64
// machinery ('+', '='). Base64 rarely contains more than one '/', while
// paths are defined by them.
func pathLike(tok string) bool {
	slashes := 0
	for _, c := range tok {
		switch c {
		case '/':
			slashes++
		case '+', '=':
			return false // base64 signature — treat as a real candidate
		}
	}
	return slashes >= 2
}

// EntropyFindings scans a file's added lines for high-entropy string
// literals / bare tokens that look like hardcoded secrets even though they
// don't match any known secret shape (Gate 3, PRD failure mode 4).
func EntropyFindings(f gitio.FileChange) []finding.Finding {
	var findings []finding.Finding
	for _, line := range f.AddedLines {
		scanned := urlPattern.ReplaceAllString(line.Text, "")
		for _, tok := range candidateTokenPattern.FindAllString(scanned, -1) {
			if pathLike(tok) || !hasDigit(tok) || shannonEntropy(tok) <= entropyThreshold {
				continue
			}
			findings = append(findings, finding.Finding{
				Gate:       gateID,
				RuleID:     "no-hardcoded-secrets/entropy",
				Severity:   finding.SeverityError,
				File:       f.Path,
				Line:       line.Number,
				Message:    fmt.Sprintf("high-entropy string literal looks like a hardcoded secret (%.1f bits/char)", shannonEntropy(tok)),
				Suggestion: "move the value to configuration/secret storage and reference it indirectly",
				RetryHint:  "Replace the high-entropy literal with a reference to a secret manager or environment variable instead of hardcoding it.",
			})
			break // one finding per line is enough signal; avoid noisy duplicates
		}
	}
	return findings
}

// shannonEntropy computes the Shannon entropy of s in bits per character:
// H = -sum(p_i * log2(p_i)) over the observed character distribution. This
// is the standard measure tools like gitleaks/truffleHog use to distinguish
// "random-looking" strings from structured or natural-language text.
func shannonEntropy(s string) float64 {
	if len(s) == 0 {
		return 0
	}
	counts := make(map[rune]int)
	for _, r := range s {
		counts[r]++
	}
	n := float64(len(s))
	var entropy float64
	for _, c := range counts {
		p := float64(c) / n
		entropy -= p * math.Log2(p)
	}
	return entropy
}
